backend:
  name: git-gateway
  branch: main
  commit_messages:
    create: 'Add blog post: "{{slug}}"'
    update: 'Update blog post: "{{slug}}"'
    delete: 'Delete blog post: "{{slug}}"'
    uploadMedia: 'Upload media: "{{path}}"'
    deleteMedia: 'Delete media: "{{path}}"'

publish_mode: editorial_workflow

site_url: https://enhancemin.com

logo:
  src: /assets/logo.png
  show_in_header: true

show_preview_links: false

media_folder: "src/assets/blog"
public_folder: "/assets/blog"

media_library:
  name: cloudinary
  config:
    cloud_name: dudif9y8i
    api_key: '948159889612615'

slug:
  encoding: "ascii"
  clean_accents: true

collections:
  - name: "blog"
    label: "Blog Posts"
    label_singular: "Blog Post"
    folder: "src/blog"
    create: true
    slug: "{{slug}}"
    preview_path: "blog/{{slug}}/"
    summary: "{{date}} · {{title}} [{{category}}]"
    sortable_fields:
      fields: ["date", "title"]
      default:
        field: date
        direction: descending
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - label: "Publish Date"
        name: "date"
        widget: "datetime"
        date_format: "YYYY-MM-DD"
        time_format: false
        format: "YYYY-MM-DD"
      - { label: "Author", name: "author", widget: "string", default: "Matt Swigart" }
      - label: "Category"
        name: "category"
        widget: "select"
        options:
          - { label: "Coaching", value: "Coaching" }
          - { label: "Ministry Life", value: "Ministry Life" }
          - { label: "Missions", value: "Missions" }
          - { label: "Devotional", value: "Devotional" }
          - { label: "Leadership", value: "Leadership" }
      - { label: "Description", name: "description", widget: "text", hint: "Brief summary shown in content card for the blog on the /blog carousel. Used for SEO (1-2 sentences)." }
      - label: "Featured Image"
        name: "featuredImage"
        widget: "image"
        required: false
        choose_url: false
        hint: "Optional. You can choose to upload a new image or select one from our Cloudinary Media Library. While this image will display in the blog preview screen, it only displays on the content card for the blog on the /blog carousel. "
      - label: "Body"
        name: "body"
        widget: "markdown"
        modes: ["rich_text", "raw"]
